//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alkemy_Challenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Time_start { get; set; }
        public int Time_end { get; set; }
        public string Teacher { get; set; }
        public int Maximum_quota { get; set; }
    }
}
